AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to launch an EC2 instance with Docker and Google Cloud SDK installed using user data

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: String
    Default: "my-key-pair"
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: "t3.micro"
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
    ConstraintDescription: must be a valid EC2 instance type.

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: "ami-0eaf7c3456e7b5b68" # Replace with a valid AMI ID for your region
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MySecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Update the package repository
          yum update -y

          # Install Docker
          amazon-linux-extras install docker -y
          service docker start
          usermod -a -G docker ec2-user

          # Ensure ec2-user has sudo privileges for Docker
          echo 'ec2-user ALL=(ALL) NOPASSWD: /usr/bin/docker' >> /etc/sudoers.d/docker

          # Install Google Cloud SDK
          tee -a /etc/yum.repos.d/google-cloud-sdk.repo <<EOF
          [google-cloud-sdk]
          name=Google Cloud SDK
          baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
                 https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          EOF

          yum install google-cloud-sdk -y

          # Add your additional configuration commands here

      Tags:
        - Key: Name
          Value: MyEC2Instance

  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0" # Adjust this to restrict access
